Resources type widget
leanspace/terraform-provider-leanspace pull request #138
Opened 2024-03-31 06:26 UTC by rohitdobariyaleanspace

2024-04-02 10:59 UTC, coutinol approved these changes

2024-04-04 15:08 UTC, jerome-leanspace requested changes
Also there some things that need to be changed
The metric used needs to have a unit and it's not present in this example could you fix it?
Also after applying when doing a second apply it seems it wants to update again

2024-04-05 04:30 UTC, rohitdobariyaleanspace commented on testing/dashboard/widgets/main.tf
> +variable "resource_id" {
Nice catch, its need to be here its comes from the resource created in the resources module...

2024-04-05 07:13 UTC, jerome-leanspace commented
> > Also there some things that need to be changed The metric used needs to have a unit and it's not present in this example could you fix it? Also after applying when doing a second apply it seems it wants to update again
> 
> You mean [here](https://github.com/leanspace/terraform-provider-leanspace/blob/f358c355794ccc3e1e2fd2f16bca761db1c0418d/examples/resources/leanspace_metrics.tf#L6), Unit is optional for numeric type.

Yes it's optional on a metric but it seems to be mandatory for a resource to be created, I don't know this service but this is an error that I got when running your terraform example

2024-04-05 07:50 UTC, rohitdobariyaleanspace commented
> > > Also there some things that need to be changed The metric used needs to have a unit and it's not present in this example could you fix it? Also after applying when doing a second apply it seems it wants to update again
> > 
> > 
> > You mean [here](https://github.com/leanspace/terraform-provider-leanspace/blob/f358c355794ccc3e1e2fd2f16bca761db1c0418d/examples/resources/leanspace_metrics.tf#L6), Unit is optional for numeric type.
> 
> Yes it's optional on a metric but it seems to be mandatory for a resource to be created, I don't know this service but this is an error that I got when running your terraform example

Yes, you are right @jerome-leanspace, in the resources if create with metric (Numeric), unit must be exists in metric..., I am suprice how it works with resources terrafrom

I will check and resolve this...

2024-04-05 13:27 UTC, jerome-leanspace approved these changes

2024-04-05 13:42 UTC, merged